### ISSUE TITLE
exporter won't connect to my freeipa_server

### ISSUE THREAD

**Issue by y0un35** [terrycain/389ds_exporter#3]
Hello,
i downloaded the exporter via go get
when i run the command "make" i get this error: 
Makefile.common:128: recipe for target '/bin/staticcheck' failed
make: *** [/bin/staticcheck] Error 127

so i tried to run the exporter with flags by running this command: 
./389ds_exporter -ipa-domain freeipa_server -ldap.user admin -ldap.pass 123456
but it only shows me the metrics of my machine like:
- go_memstats_alloc_bytes 
- go_memstats_gc_cpu_fraction 
- process_virtual_memory_max_bytes 
- promhttp_metric_handler_requests_total

when i run the following command:
./389ds_exporter -ipa-domain freeipa_server -ldap.user "freeipa_user" -ldap.pass "password" -web.listen-address "freeipa_server"
i get this error:
ERRO[0078] Scrape failed, error is:unable to read LDAP response packet: unexpected EOF

PS: i installed the exporter in my prometheus server, it's not necessary to install it in the freeipa_server?

Thanks in advance

**Comment by terricain** [comment]
https://github.com/terrycain/389ds_exporter/releases there are some premade binaries here, does any of them work?
